jobs:
  include:
  - stage: Build

    sudo: required
    services:
    - docker
    script: docker build --build-arg CODECOV_TOKEN --build-arg "APP_VERSION=$(make version)" -t "${DOCKER_USER}/$(make name):$(make version)" .
    after_success:
    - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
    - docker push "${DOCKER_USER}/$(make name):$(make version)"

  - stage: Publish

    sudo: required
    services:
    - docker
    script:
    - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
    - docker pull "${DOCKER_USER}/$(make name):$(make version)"
    - docker tag "${DOCKER_USER}/$(make name):$(make version)" "${DOCKER_USER}/$(make name):latest"
    - docker push "${DOCKER_USER}/$(make name):latest"
    after_success:
    - curl -q -sSL --max-time 10 -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/goweb

  - stage: Deploy

    script: |
     sed \
        -e "s|\${DOCKER_USER}|${DOCKER_USER}|g" \
        -e "s|\${DOMAIN}|${DOMAIN}|g" \
        -e "s|\\\$|\$\$|g" \
        docker-compose.yml > docker-compose-env.yml
    deploy:
      provider: script
      skip_cleanup: true
      script: bash script/deploy "$(make name)" "@docker-compose-env.yml"

stages:
- Build
- name: Publish
  if: branch = master && type = push
- name: Deploy
  if: false

notifications:
  email: false
