apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goweb
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.90"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: goweb
    image:
      name: vibioh/goweb
      tag: "202305281311" # {"$imagepolicy": "default:flux-goweb-api:tag"}
    config:
      API_LOGGER_JSON: "true"
      API_TRACER_URL: otel-collector.observability:4317
      GOMAXPROCS: "1"
      OTEL_SERVICE_NAME: goweb
    ingress:
      enabled: true
      compress: true
      hosts:
        - api.vibioh.fr
    pprof:
      enabled: true
