apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goweb
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.69"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: goweb
    image:
      name: vibioh/goweb
      tag: "202105110810" # {"$imagepolicy": "default:flux-goweb-api:tag"}
    config:
      API_LOGGER_JSON: "true"
    ingress:
      enabled: true
      hosts:
      - api.vibioh.fr
    canary:
      enabled: true
      url: http://api.vibioh.fr/hello/
