apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goweb
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.42"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m
  values:
    nameOverride: goweb
    image:
      repository: vibioh/goweb:latest # {"$imagepolicy": "default:goweb"}
    config:
      API_LOGGER_JSON: "true"
    ingress:
      enabled: true
      hosts:
      - api.vibioh.fr
