---
apiVersion: v1
kind: Service
metadata:
  name: goweb
  labels:
    app.kubernetes.io/name: goweb
    app.kubernetes.io/instance: goweb
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    name: goweb
  ports:
    - name: http
      port: 80
      targetPort: http
