---
namespace: default

image:
  repository: vibioh/goweb
  pullPolicy: Always

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/scheme: http
  prometheus.io/port: "1080"

livenessProbePath: /health
readinessProbePath: /health

config: {}

resources:
  limits:
    cpu: 100m
    memory: 64M
  requests:
    cpu: 100m
    memory: 64M

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - goweb.vibioh.fr

pod_disruption:
  enabled: true
  minAvailable: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
