---
name: Dependabot Pull Request

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - run: exit 0
