{{- if .Values.Config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.Config | nindent 2 }}
{{ end }}
