---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goweb.fullname" . }}
  labels:
    {{- include "goweb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "goweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "goweb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 1080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "{{ .Values.livenessProbePath }}"
              port: http
          readinessProbe:
            httpGet:
              path: "{{ .Values.readinessProbePath }}"
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
