---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.config }}
        checksum/config: {{ toYaml . | sha256sum }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.config .Values.secretRef }}
          envFrom:
            - configMapRef:
                name: {{ include "app.fullname" . }}
          {{- end }}
          {{- if .Values.secretRef }}
            - secretRef:
                name: {{ .Values.secretRef }}
          {{- end }}
          ports:
            - name: http
              containerPort: 1080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "{{ .Values.livenessProbePath }}"
              port: http
          readinessProbe:
            httpGet:
              path: "{{ .Values.readinessProbePath }}"
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
