{{- if .Values.ingress.enabled -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "goweb.fullname" . }}-http
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "goweb.labels" . | nindent 4 }}
spec:
  entryPoints:
    - http
  routes:
    - match: {{ include "ingress.hosts" . }}
      kind: Rule
      middlewares:
        - name: redirect
      services:
        - name: {{ include "goweb.fullname" . }}
          namespace: {{ .Values.namespace }}
          port: {{ .Values.service.port }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "goweb.fullname" . }}-https
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "goweb.labels" . | nindent 4 }}
spec:
  entryPoints:
    - https
  routes:
    - match: {{ include "ingress.hosts" . }}
      kind: Rule
      middlewares:
        - name: compress
        - name: ratelimit
      services:
        - name: {{ include "goweb.fullname" . }}
          namespace: {{ .Values.namespace }}
          port: {{ .Values.service.port }}
  tls:
    certResolver: default
{{- end -}}
